AWSTemplateFormatVersion: "2010-09-09"
 Description: ECR repo test WM Golang Test
 Resources:
   AWSTrainingTestRepo:
     Type: AWS::ECR::Repository
     Properties:
       RepositoryName: "max-golang"
 Outputs:
   AWSTrainingTestArn:
     Value: !GetAtt AWSTrainingTestRepo.Arn
     Export:
       Name: AWSTrainingTestArn